# -- PostgreSQL Configuration --
# spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
# spring.datasource.username=_your_username
# spring.datasource.password=your_password
# spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
server.servlet.context-path=/api/v1.0

spring.config.import=optional:file:.env
allowed.origin=${ALLOWED_ORIGIN}
base.url=${BASE_URL}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret.key=${JWT_SECRET_KEY}

aws.access.key=${aws.access.key}
aws.secret.key=${aws.secret.key}
aws.region=${aws.region}
aws.bucket.name=${aws.bucket.name}

razorpay.key.id=${razorpay.key.id}
razorpay.key.secret=${razorpay.key.secret}